cc=gcc
main:main.o diff.o pro.o sum.o
	$(cc) -o main main.o diff.o pro.o sum.o
main.o:main.c
	$(cc) -o main.o -c main.c
diff.o:diff.c
	$(cc) -o diff.o -c diff.c
pro.o:pro.c	
	$(cc) -o pro.o -c pro.c
sum.o:sum.c
	$(cc) -o sum.o -c sum.c